### ISSUE TITLE
Feature wish: view all messages in the topic

### ISSUE THREAD

**Issue by privettoli** [mvmn/mvmvKafkaGUI#3]
More than often I'm interested not in a particular partition but in the messages that the topic contains. I have many partitions (from 24 to 1xx). I'd like to be able to view all messages in the topic instead of going over every partition. I understand that internally we'll have to check all partitions and I'm okay to wait if it's done in a concurrent fashion.

**Comment by mvmn** [comment]
Sounds good, will add

**Comment by mvmn** [comment]
Done
https://github.com/mvmn/mvmnKafkaGUI/releases/tag/0.0.4
