### ISSUE TITLE
Don't wait for messages during poll or provide customization for poll timeout

### ISSUE THREAD

**Issue by privettoli** [mvmn/mvmvKafkaGUI#4]
When I don't have messages in my topic partitions (assuming I have 100 partitions):
Expected behavior: I instantly can see that there's no messages (button unpressed).
Actual behavior: button stays pressed and I have to wait quite a while until I can find a message (or no messages) in the very last partition.

**Comment by mvmn** [comment]
Not sure how to reproduce this - I've just created a new blank topic with 10 partitions, and "Get messages" on it returns immediately.
Can you let me know which version of Kafka are you running?

**Comment by privettoli** [comment]
@mvmn 
https://github.com/mvmn/mvmnKafkaGUI/blob/master/src/main/java/x/mvmn/kafkagui/gui/KafkaAdminGui.java#L360
```java
List<ConsumerRecord<String, byte[]>> page = consumer.poll(Duration.ofSeconds(5)).records(tp);
```
https://kafka.apache.org/24/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#poll-java.time.Duration-
> This method returns immediately if there are records available. Otherwise, it will await the passed timeout. If the timeout expires, an empty record set will be returned.

**Comment by privettoli** [comment]
Oops… so we're checking offset before that. Then most probably it's a latency problem I experience.
Would it be possible to make the polling async for all topics?

**Comment by mvmn** [comment]
Yes, we do check offsets beforehand.

So, what is your Kafka version?

I'm also considering parallelizing reading offsets for partitions, since this is sequential, and for 100 partitions even just reading offsets might take a while. But this will take a bit to implement properly.

**Comment by mvmn** [comment]
Actually, scratch that. Working on all offsets in parallel turns out to be "super easy, barely an inconvenience".
I'll publish a new release in a few minutes.

**Comment by mvmn** [comment]
@privettoli , https://github.com/mvmn/mvmnKafkaGUI/releases/tag/0.0.5

**Comment by privettoli** [comment]
@mvmn excellent, works much better now. Kafka version: 2.5.1
